---
title: "Lab 2 - Data wrangling"
author: "Aiden Mansfield"
date: "June 24, 1497"
format: 
  html: default # for speed
  pdf: default # for final output

---


```{r}
#| eval: true
#| message: false

library(tidyverse)
```


# Questions

## Part 1

### Question 1

```{r}

library(dplyr)

state_count <- midwest |> 
  group_by(state) |> 
  summarize(county_numbers = n()) |> 
  arrange(desc(county_numbers))
print("Number of counties in each state in descending order of number of counties")
print(state_count)

highest <- midwest |> 
  group_by(state) |> 
  summarize(county_numbers = n()) |> 
  ungroup() |> 
  slice_max(county_numbers, n = 1)
print("Highest number of counties")
print(highest)

lowest <- midwest |> 
  group_by(state) |> 
  summarize(county_numbers = n()) |> 
  ungroup() |> 
  slice_min(county_numbers, n = 1)
print("Lowest number of counties")
print(lowest)

```


\newpage

### Question 2

\newpage

### Question 3
\newpage

### Question 5

\newpage

### Question 6

\newpage

### Question 7

\newpage

### Question 8

\newpage

## Part 2


### Question 9

